name: eCommerceApplication/Release_PaymentProcessor
on:
  push:
    branches:
    - main
  workflow_dispatch:  
env:
  azureSubscription: "<<AzureServiceConnectionName>>"
  buildConfiguration: Release
  webAppNameDev: "<<webapp-dev-name>>"
  webAppNameProd: "<<webapp-prod-name>>"
  webAppNameQa: "<<webapp-qa-name>>"
  webAppNameStaging: "<<webapp-staging-name>>"
jobs:
  Dev-DeployToDev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment:
      name: dev
    
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
      
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
      
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
        
    - name: dotnet publish (API)
      run: dotnet publish PaymentProcessor.Api/PaymentProcessor.Api.csproj -c ${{ env.buildConfiguration }} -o ${{ runner.workspace }}\artifacts
      
    - name: Deploy to Dev
        
       
  QA-DeployToQa:
    name: Deploy to QA
    needs:
    - Dev-DeployToDev
    runs-on: ubuntu-latest
    environment:
      name: qa
    if: success()
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
      
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
      
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
        
    - name: dotnet publish (API)
      run: dotnet publish PaymentProcessor.Api/PaymentProcessor.Api.csproj -c ${{ env.buildConfiguration }} -o ${{ runner.workspace }}\artifacts
      
    - name: Deploy to QA

        
       
  Staging-DeployToStaging:
    name: Deploy to Staging
    needs:
    - QA-DeployToQa
    runs-on: ubuntu-latest
    environment:
      name: staging
    if: success()
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
      
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
      
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
        
    - name: dotnet publish (API)
      run: dotnet publish PaymentProcessor.Api/PaymentProcessor.Api.csproj -c ${{ env.buildConfiguration }} -o ${{ runner.workspace }}\artifacts
      
    - name: Deploy to Staging
        
  Prod-DeployToProd:
    name: Deploy to Prod
    needs:
    - Staging-DeployToStaging
    runs-on: ubuntu-latest
    environment:
      name: prod
    if: success()
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
      
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
      
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
        
    - name: dotnet publish (API)
      run: dotnet publish PaymentProcessor.Api/PaymentProcessor.Api.csproj -c ${{ env.buildConfiguration }} -o ${{ runner.workspace }}\artifacts
      
    - name: Deploy to Prod

